# Generated by Django 4.0.4 on 2022-05-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='URL фигуры')),
                ('image', models.ImageField(upload_to='media', verbose_name='Картинка')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Накопления')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='URL измерения')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Накопления'),
        ),
    ]
