# Generated by Django 4.0.4 on 2022-05-12 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_communication', '0002_figure_type_customuser_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_communication.type', verbose_name='Измерение'),
        ),
        migrations.AddField(
            model_name='figure',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
