# Generated by Django 4.0.4 on 2022-05-14 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_communication', '0003_figure_type_figure_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='URL figure'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_communication.type', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='FigureBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_communication.figure', verbose_name='Figure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
