# Generated by Django 4.0.4 on 2022-05-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_communication', '0004_alter_figure_cost_alter_figure_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes'),
        ),
        migrations.CreateModel(
            name='FigureLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_communication.figure', verbose_name='Figure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
